spring:
  application:
    name: mscartoes
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER}:3306/dbmicroservices
    username: root
    password: root
  jpa:
     hibernate.ddl-auto: update
     generate-ddl: true
     show-sql: true
     properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest
    server:
  port: 0
  error:
    include-stacktrace: ON_PARAM

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ms-user-eureka:-euemkasreurs-@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: ./logs/log-file.log

