spring:
  application:
    name: eurekaserver
  security:
    user:
      name: ms-user-eureka
      password: -euemkasreurs-

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
