spring:
  application:
    name: gateway
  security:    oauth2:      resourceserver:        jwt:          issuer-uri: http://curso-ms-keycloak:8081/realms/msrealm
  cloud:
    gateway:
      discovery:        locator:          enabled: true
          lower-case-service-id: true
  
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ms-user-eureka:-euemkasreurs-@eureka:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

